### ISSUE TITLE
PAT v.0.24.3 Draft202012Validator Import Error

### ISSUE THREAD

**Issue by jamesejr** [panther-labs/panther_analysis_tool#330]
### Describe the bug

The latest release of PAT v0.24.3 breaks when running `panther_analysis_tool --version` in CI. After updating, the following error is thrown:

```
Run panther_analysis_tool --version
Traceback (most recent call last):
  File "/home/runner/.local/bin/panther_analysis_tool", line 3, in <module>
    from panther_analysis_tool import main
  File "/home/runner/.local/lib/python3.10/site-packages/panther_analysis_tool/main.py", line 57, in <module>
    from jsonschema.validators import Draft202012Validator
ImportError: cannot import name 'Draft202012Validator' from 'jsonschema.validators' (/usr/lib/python3/dist-packages/jsonschema/validators.py)
Error: Process completed with exit code 1.
```

It looks to be related to https://github.com/panther-labs/panther_analysis_tool/pull/328

### Steps to reproduce

1. Upgrade PAT to the latest version
2. Setup a GitHub Actions workflow to install PAT
3. Print the version `panther_analysis_tool --version` in the workflow

### Expected behavior

I expect to see the latest version printed to console.

### Environment

How are you deploying or using Panther?

- Panther version or commit: v.0.24.3
- OS: Ubuntu (`ubuntu-latest` in GitHub Action)

### Additional context

The problem seems to be only via CI. It seems to work fine when upgrading and testing on my local machine and this wasn't an issue in CI prior to upgrading to the latest version of PAT.

### Screenshots

N/A

**Comment by jamesejr** [comment]
False alarm. Turns out the solution was to upgrade to Python 3.11 in GitHub Actions. Closing this issue.
